<script>
import HelloFriend from "./islands/HelloFriend.svelte"
import Counter from "./islands/Counter.svelte"

/** @type {'HelloFriend' | 'Counter'} */
export let name;
/** @type {Record<string, unknown>} */
export let props;

/** this is auto-generated by the build script */
const islands = {
HelloFriend,
Counter
};
</script>

<one-claw {name} props={JSON.stringify(props)}>
<svelte:component this={islands[name]} {...props} />
</one-claw>
